# Generated by Django 4.2.6 on 2024-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sche', '0002_remove_user_salt_appointment_isdeleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], default='Patient', max_length=10, null=True),
        ),
    ]
